name: Automatic Profile Serial Bump

on:
  push:
    branches: ["main"]
    paths: ["vATIS Profile - LOVV.json"]

jobs:
  bump-serial:
    name: Automatic Profile Serial Bump
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run script
        run: python .github/workflows/serial-bump.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "vATIS Profile - LOVV.json"
          git commit -m "chore: bump serial number & profile name"
          git push
